### ISSUE TITLE
Initial home screen

### ISSUE THREAD

**Issue by alexs** [BC-MAY-21-ROR/proyecto-final-pf-f22-t3#8]
# REQUIREMENTS
As user I want to access directly to games after login to select which game play.

# DESIGN
We have to show in the home screen a grid with four cards or as many games we have. The cards represents and directly access to the game. The card could have and image and title.

Home:
_________________________
|                       |                        |
|   Game 1       |   Game 2        |
|________________________
|                        |                       |
|   Game 3       |   Game 4       |
|________________________|

# Acceptance Criteria
List all required acceptance criteria
- [ ] Have minimal one direct access
- [ ] Must be the home screen

**Comment by alanRazoMen** [comment]
close #10
